# 使用预构建镜像的Docker Compose配置
# 避免构建过程中的网络问题

version: '3.8'

services:
  # 使用预构建的应用镜像
  vue-fastapi-admin:
    # 选项1: 使用本地构建的镜像
    image: vue-fastapi-admin:latest
    # 选项2: 使用远程仓库的镜像（如果有）
    # image: registry.cn-hangzhou.aliyuncs.com/your-namespace/vue-fastapi-admin:latest
    
    container_name: vue-fastapi-admin
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - LANG=zh_CN.UTF-8
      - TZ=Asia/Shanghai
      - DEBUG=false
    volumes:
      - ./db.sqlite3:/opt/vue-fastapi-admin/db.sqlite3
      - ./logs:/opt/vue-fastapi-admin/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network

  # 使用中国镜像源的Nginx
  nginx:
    image: hub-mirror.c.163.com/library/nginx:alpine
    container_name: vue-fastapi-admin-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./deploy/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - vue-fastapi-admin
    networks:
      - app-network

  # 使用中国镜像源的Redis
  redis:
    image: hub-mirror.c.163.com/library/redis:alpine
    container_name: vue-fastapi-admin-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
